x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 50

services:
  postgres:
    restart: always
    logging: *default-logging
    environment:
      POSTGRES_PASSWORD: postgres
    image: pgvector/pgvector:0.8.1-pg18
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    restart: always
    logging: *default-logging
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/chuckhend/vectorize-server:latest
    ports:
      - 8080:8080
    environment:
      HF_API_KEY: ${HF_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CO_API_KEY: ${CO_API_KEY}
      VOYAGE_API_KEY: ${VOYAGE_API_KEY}
      EMBEDDING_SVC_URL: ${EMBEDDING_SVC_URL:-http://vector-serve:3000/v1}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/postgres}
      RUST_LOG: debug
    command: vectorize-server
  vector-serve:
    restart: always
    logging: *default-logging
    image: ghcr.io/chuckhend/vector-serve:latest
    ports:
      - 3000:3000
