services:
  postgres:
    restart: always
    image: quay.io/tembo/vectorize-pg:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  vector-serve:
    restart: always
    image: quay.io/tembo/vector-serve:latest
    ports:
      - 3000:3000
  ollama-serve:
    image: quay.io/tembo/ollama-serve:latest
    ports:
      - 3001:3001
    environment:
      - OLLAMA_HOST=0.0.0.0:3001
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]



# Path: Dockerfile
  hf-serve:
    ports:
      - 8081:80
    image: ghcr.io/huggingface/text-generation-inference:2.0
    command: ["--model-id HuggingFaceH4/zephyr-7b-beta"]
    shm_size: 1g
