site_name: Vectorize
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: light mode
nav:
  - Vectorize: 'index.md'
  - API: 
    - Overview: 'api/index.md'
    - 'api/search.md'
    - 'api/rag.md'
    - 'api/utilities.md'
  - Examples: 
    - Search:
      - 'examples/sentence_transformers.md'
      - 'examples/openai_embeddings.md'
      - 'examples/scheduling.md'
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- codehilite:
- admonition
- extra
- pymdownx.snippets:
    check_paths: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
plugins:
  - search
  - mkdocstrings
