site_name: Vectorize
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: light mode
nav:
  - Vectorize: 'index.md'
  - Server:
    - API:
      - Table: 'server/api/table.md'
      - Search: 'server/api/search.md'
  - Extension:
    - API:
      - Overview: 'extension/api/index.md'
      - Search: 'extension/api/search.md'
      - RAG: 'extension/api/rag.md'
      - Utilities: 'extension/api/utilities.md'
    - Model Providers: 'extension/models/index.md'
    - Examples:
      - Search:
        - Sentence Transformers: 'extension/examples/sentence_transformers.md'
        - OpenAI Embeddings: 'extension/examples/openai_embeddings.md'
        - Scheduling: 'extension/examples/scheduling.md'
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- codehilite:
- admonition
- extra
- pymdownx.snippets:
    check_paths: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
plugins:
  - search
  - mkdocstrings
