name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: Build and push images
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    outputs:
      short_sha: ${{ steps.versions.outputs.SHORT_SHA }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and upload image
        run: |
          docker build -t vector-serve .
          docker tag vector-serve quay.io/tembo/vector-serve:${{ steps.versions.outputs.short_sha }}
          docker tag vector-serve quay.io/tembo/vector-serve:latest
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io/tembo
          username: ${{ secrets.QUAY_USER_TEMBO }}
          password: ${{ secrets.QUAY_PASSWORD_TEMBO }}
      - name: Push image
        run: |
          docker push quay.io/tembo/vector-serve:${{ steps.versions.outputs.short_sha }}
          docker push quay.io/tembo/vector-serve:latest
