name: Docs CI Workflow
on:
  push:
    branches:
      - main
      - apr-doc
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.1 python3 -
      - run: poetry install
      - run: poetry run mkdocs gh-deploy
