name: Docs CI Workflow
on:
  push:
    branches:
      - main
      - apr-doc
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=${POETRY_VERSION} python3 -
      - run: poetry install
      - run: poetry mkdocs gh-deploy
