name: Extension Upgrade

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test:
    name: Upgrade Test
    runs-on: ubuntu-22.04
    services:
      vector-serve:
        image: quay.io/tembo/vector-serve:latest
        ports:
          - 3000:3000
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "extension-upgrade-test"
          workspaces: |
            vectorize
          # Additional directories to cache
          cache-directories: |
            /home/runner/.pgrx
      - name: Get current version
        id: current-version
        run: echo "CI_BRANCH=$(git name-rev --name-only HEAD)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/pgx-init
        with:
          working-directory: ./
      - name: Install sys dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-server-dev-14
          make setup
      - name: Test previous version (main))
        run: |
          git fetch --tags
          git checkout main
          echo "\q" | make run
          cargo test -- --ignored --test-threads=1
      - name: Test branch's version
        env:
          CI_BRANCH: ${{ steps.current-version.outputs.CI_BRANCH }}
        run: |
          git checkout $CI_BRANCH
          make test-update
      - name: Debugging information
        if: always()
        env:
          CI_BRANCH: ${{ steps.current-version.outputs.CI_BRANCH }}
        run: |
          git checkout $CI_BRANCH
          make cat-logs
