name: PG Vectorize Extension

defaults:
  run:
    shell: bash
    working-directory: ./extension

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/extension_ci.yml"
      - "extension/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/extension_ci.yml"
      - "extension/**"
  release:
    types:
      - created
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust minimal nightly with clippy and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "pg-vectorize-extension-lint"
          workspaces: pg-vectorize/
          # Additional directories to cache
          cache-directories: /home/runner/.pgrx
      - uses: ./.github/actions/pgx-init
        with:
          working-directory: ./extension
      - name: Cargo format
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy

  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      vector-serve:
        image: ghcr.io/chuckhend/vector-serve:latest
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            vectorize
          # Additional directories to cache
          cache-directories: |
            /home/runner/.pgrx
      - name: Install sys dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libreadline-dev zlib1g-dev flex bison libclang-dev postgresql-client libicu-dev make wget pkg-config libssl-dev git gcc libopenblas-dev
      - uses: ./.github/actions/pgx-init
        with:
          working-directory: ./extension
      - name: setup-tests
        run: |
          make setup
      - name: unit-test
        run: |
          echo "\q" | make run
          make test-unit
      - name: integration-test
        if: github.repository_owner == 'ChuckHend'
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          CO_API_KEY: ${{ secrets.CO_API_KEY }}
          PORTKEY_API_KEY: ${{ secrets.PORTKEY_API_KEY }}
          PORTKEY_VIRTUAL_KEY_OPENAI: ${{ secrets.PORTKEY_VIRTUAL_KEY_OPENAI }}
          VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
        run: make test-integration
